# -*- coding: utf-8 -*-
"""sistem panen (TTS 4)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUNl6uoduZrh4WYmpSgq5jG9Imx4pW30
"""

# main.py
def hitung_total_panen(panen_pagi, panen_sore):
    return panen_pagi + panen_sore

if __name__ == "__main__":
    total = hitung_total_panen(120, 80)
    print(f"Total Hasil Panen: {total} kg")
def hitung_diskon_maksimal(harga_awal, persentase_diskon, maks_potongan):
    potongan = harga_awal * (persentase_diskon / 100)

    # Batasi nilai potongan jika melebihi batas maksimal
    if potongan > maks_potongan:
        potongan = maks_potongan

    harga_akhir = harga_awal - potongan
    return harga_akhir, potongan

# Contoh penggunaan:
harga_barang = 100000
diskon_persen = 50  # 50% dari 100rb seharusnya 50rb
maksimal_potongan = 20000  # tapi dibatasi maksimal 20rb

harga_bayar, potongan_dapat = hitung_diskon_maksimal(harga_barang, diskon_persen, maksimal_potongan)
print(f"Harga Barang: Rp{harga_barang:,}")
print(f"Potongan Didapat: Rp{potongan_dapat:,}")
print(f"Total Bayar: Rp{harga_bayar:,}")
